-- AlterTable
ALTER TABLE "Bet" ADD COLUMN     "claimed" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "doubtPool" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "platformFee" DOUBLE PRECISION NOT NULL DEFAULT 0.01,
ADD COLUMN     "supportPool" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalPool" DOUBLE PRECISION NOT NULL DEFAULT 0;
