[package]
name = "nft_validation_platform"
version = "1.0.0"
authors = ["Adarsh Dhar dharadarsh0@gmail.com"]

[addresses]
nft_validation = "0x0063243a137391971e67b67ea8e2de564145781363a24071a57f74e755b750b7"
aptos_framework = "0x1"
aptos_token = "0x3"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "main" }